#pragma once

#include "../__detect.h"

// ESP32階層の検出マクロ
#ifndef FLEXHAL_DETECT_HARDWARE_CHIP_ESPRESSIF_ESP32_ESP32S3
 #if FLEXHAL_DETECT_HARDWARE_CHIP_ESPRESSIF_ESP32
  #if defined(CONFIG_IDF_TARGET_ESP32S3) || defined(ARDUINO_ESP32S3_DEV)
   #define FLEXHAL_DETECT_HARDWARE_CHIP_ESPRESSIF_ESP32_ESP32S3 1
  #else
   #define FLEXHAL_DETECT_HARDWARE_CHIP_ESPRESSIF_ESP32_ESP32S3 0
  #endif
 #else
  #define FLEXHAL_DETECT_HARDWARE_CHIP_ESPRESSIF_ESP32_ESP32S3 0
 #endif
#endif
